### ISSUE TITLE
Build trouble on Linux

### ISSUE THREAD

**Issue by RandomInsano** [o8vm/rust_dos#4] opened 2021-03-06 03:59 UTC
Followed the README. Doesn't seem to want to build for me on Ubuntu 20.04:

```
$ cargo +nightly build --verbose --release
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -C link-arg=-Tlink.x --target /home/edwinamsler/Documents/Code/rust/other/rust_dos/i586-rust_dos.json --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
  --- stderr
  error: Error loading target specification: `Boolean(true)` is not a valid value for `stack-probes`: expected a JSON object. Use `--print target-list` for a list of built-in targets
```

Rust versions:
```
$ cargo --version
cargo 1.52.0-nightly (c68432f1e 2021-03-02)
$ rustc --version
rustc 1.52.0-nightly (caca2121f 2021-03-05)
```

**Comment by turbocat2001** [comment] 2021-03-27 09:09
A similar problem.

**Comment by turbocat2001** [comment] 2021-03-27 09:13
> stack-probes

If you remove the 'stack-probes' then it seems like it works

**Comment by o8vm** [comment] 2021-03-29 16:40
@RandomInsano Thanks reporting！
@turbocat2001 Do you have a pull request? I'll merge it!

**Comment by nitsuga5124** [comment] 2021-04-07 21:05
using cross to build via `cross build --target x86_64-pc-windows-gnu` makes it start compiling, but ends up erroring with:
```
   Compiling rust_dos v0.1.0 (/project)
error: language item required, but not found: `eh_personality`

error: aborting due to previous error

error: could not compile `rust_dos`

To learn more, run the command again with --verbose.
```

**Comment by RandomInsano** [comment] 2021-04-09 01:55
Created an MR. I'm having *other* problems. But that first one is gone. :D

**Comment by o8vm** [comment] 2021-04-12 08:36
Thanks @RandomInsano for creating MR. I've merged it. 
I'm closing this issue. For other issues, please create a new issue. 

@nitsuga5124 That looks like a different issue. I've never used cross before, so can you open a new issue and give me the environment info and steps to reproduce?

**Closed by o8vm** 2021-04-12 08:36 UTC
